microservice:
  ports:
    auth: ${AUTH_SERVICE_PORT:8081}
    notification: ${NOTIFICATION_SERVICE_PORT:8082}
    asset: ${ASSET_SERVICE_PORT:8085}
    helpdesk: ${HELPDESK_SERVICE_PORT:8084}

spring:
  application:
    name: common-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

auth:
  service:
    url: http://localhost:${microservice.ports.auth}

asset:
  service:
    url: http://localhost:${microservice.ports.asset}

notification:
  service:
    url: http://localhost:${microservice.ports.notification}/api/notifications

JWT_PRIVATE_KEY_PATH: classpath:keys/jwt-private.pem
JWT_PUBLIC_KEY_PATH: classpath:keys/jwt-public.pem
JWT_SECRET: yNnC7M3ZqgV4bD0lFJm9Q2w5tSe8XpR1pWc7UjK4oHs=
JWT_ACCESS_TOKEN_VALIDITY_SECONDS: 900
JWT_REFRESH_TOKEN_VALIDITY_SECONDS: 1209600
AUTH_ENC_KEY: SLOqKf8lS2hidTDsXQe25ZSaoaGcczUX6gySXUxjE1M=
AUTH_HMAC_KEY: krFcA7/MYPXQWbtSGMM87Dzxu2euOsRckVFeUyOC6dw=
