-- Templates
CREATE TABLE IF NOT EXISTS notification_template_master (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  template_code VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255),
  subject VARCHAR(255),
  body TEXT NOT NULL,
  placeholders JSON,
  active BOOLEAN DEFAULT TRUE,
  project_type ENUM('ECOM','ASSET_MGMT') NOT NULL DEFAULT 'ECOM',
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sms_template_master (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  template_code VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255),
  subject VARCHAR(255),
  body TEXT NOT NULL,
  placeholders JSON,
  active BOOLEAN DEFAULT TRUE,
  project_type ENUM('ECOM','ASSET_MGMT') NOT NULL DEFAULT 'ECOM',
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_template_master (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  template_code VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255),
  subject VARCHAR(255),
  body TEXT NOT NULL,
  placeholders JSON,
  active BOOLEAN DEFAULT TRUE,
  project_type ENUM('ECOM','ASSET_MGMT') NOT NULL DEFAULT 'ECOM',
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inapp_template_master (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  template_code VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255),
  title VARCHAR(255),
  subject VARCHAR(255),
  body TEXT NOT NULL,
  placeholders JSON,
  active BOOLEAN DEFAULT TRUE,
  project_type VARCHAR(50) NOT NULL DEFAULT 'ECOM',
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Logs
CREATE TABLE IF NOT EXISTS sms_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  mobile VARCHAR(255),
  mobileFingerprint VARCHAR(255),
  message TEXT,
  template_code VARCHAR(100),
  provider_message_id VARCHAR(255),
  provider_response TEXT,
  retries INT DEFAULT 0,
  user_id VARCHAR(64),
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  email VARCHAR(255),
  emailFingerprint VARCHAR(255),
  subject VARCHAR(255),
  message TEXT,
  channel VARCHAR(50),
  template_code VARCHAR(100),
  provider_response TEXT,
  user_id VARCHAR(64),
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  mobile VARCHAR(255),
  mobileFingerprint VARCHAR(255),
  message TEXT,
  template_code VARCHAR(100),
  provider_response TEXT,
  user_id VARCHAR(64),
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inapp_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  title VARCHAR(255),
  message TEXT,
  template_code VARCHAR(100),
  user_id VARCHAR(64),
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  entity_name VARCHAR(100) NOT NULL,
  entity_id BIGINT NOT NULL,
  action ENUM('CREATE','UPDATE','DELETE','READ') NOT NULL,
  old_value JSON,
  new_value JSON,
  ip_address VARCHAR(100),
  user_agent VARCHAR(512),
  url VARCHAR(1024),
  http_method VARCHAR(10),
  user_id VARCHAR(64),
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

